DROP DATABASE IF EXISTS Nimesuki;
CREATE DATABASE IF NOT EXISTS Nimesuki;
USE Nimesuki;

CREATE TABLE Anime (
  id_anime INT PRIMARY KEY auto_increment, 
  nombre VARCHAR(50) NOT NULL,
  categorias VARCHAR(150),
  anho_salida INT,
  descripcion VARCHAR(1000) NOT NULL,
  imagen VARCHAR(100),
  cap_totales INT NOT NULL
);

CREATE TABLE Usuario (
  id_usuario INT PRIMARY KEY auto_increment, 
  nombre VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  contrasenha VARCHAR(60) NOT NULL,
  tipo ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER'
);

CREATE TABLE Favoritos (
  id_anime_FK INT,
  id_usuario_FK INT,
  valoracion FLOAT,       
  cap_actual INT,        
  PRIMARY KEY (id_usuario_FK, id_anime_FK),
  FOREIGN KEY (id_anime_FK) REFERENCES anime(id_anime),
  FOREIGN KEY (id_usuario_FK) REFERENCES usuario(id_usuario)
);

INSERT INTO Anime (nombre, categorias, anho_salida, descripcion, imagen, cap_totales) VALUES
('Re:Zero kara Hajimeru Isekai Seikatsu', 'Acción, Fantasía, Isekai, Drama, Psicológico, Sobrenatural, Romance, Aventura', 2016, 'Subaru Natsuki es un estudiante corriente de preparatoria que conoce a una hermosa chica de pelo plateado de otro mundo que lo rescata. Para devolverle el favor decide quedarse con ella, pero el destino con el que carga la muchacha es mucho más pesado de lo que Subaru puede imaginar. Los enemigos atacan sin descanso, uno tras otro, hasta que finalmente mueren tanto él como la chica. Subaru no quiere que la chica resulte herida, con lo que jura acabar con cualquier enemigo, con cualquier destino que le aguarde, siempre por protegerla.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/re_zero_t1.jpg', 25),
('Re:Zero kara Hajimeru Isekai Seikatsu: Memory Snow', 'Acción, Fantasía, Isekai, Drama, Psicológico, Sobrenatural, Romance, Aventura', 2018, 'Después de los intensos eventos ocurridos en la mansión de Roswaal, Subaru finalmente obtiene un merecido descanso y porfin podrá tener su cita con Emilia. Sin embargo, esta no podrá realizarse ya que Pack tiene su temporada de hatsumaki, A causa de eso, Subaru se le ocurre una idea: ¡hacer un festival de nieve en la mansión Roswaal!', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/re_zero_memory_snow.jpg', 1),
('Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season', 'Acción, Fantasía, Isekai, Drama, Psicológico, Sobrenatural, Romance, Aventura', 2020, 'Después de derrotar al Arzobispo de la Pereza, Subaru y Emilia regresan a la aldea, solo para encontrarla devastada y a Rem en coma, olvidada por todos menos por Subaru. En busca de respuestas, se dirigen al Santuario, donde Subaru enfrenta duras pruebas y conoce a la Bruja de la Codicia, Echidna. Mientras tanto, nuevas amenazas se ciernen sobre ellos, poniendo a prueba su determinación y vínculos.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/re_zero_t2.jpg', 25),
('Re:Zero kara Hajimeru Isekai Seikatsu 3rd Season', 'Acción, Fantasía, Isekai, Drama, Psicológico, Sobrenatural, Romance, Aventura', 2025, 'Ha pasado un año desde la victoria de Subaru en el Santuario. Disfruta de una vida plena mientras el grupo de Emilia se mantiene unido para la selección real, hasta que llega una carta fatídica. Anastasia, una candidata a la selección real, ha invitado a Emilia a la ciudad Watergate de Priestella. Pero cuando el grupo comienza su viaje, la crisis se agita bajo la superficie y Subaru se enfrenta a un destino cruel una vez más.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/re_zero_t3.jpg', 16),
('Shingeki no kyojin', 'Acción, Drama, Fantasía, Supervivencia, Misterio, Psicológico, Aventura, Shounen', 2013, 'En un mundo donde la humanidad está al borde de la extinción, los sobrevivientes viven dentro de murallas gigantes para protegerse de los titanes, monstruos que devoran humanos sin piedad. Eren Jaeger, junto a su hermana adoptiva Mikasa y su amigo Armin, se une al ejército tras la destrucción de su ciudad. Juntos lucharán por sobrevivir y descubrir los secretos oscuros de los titanes, mientras se enfrentan a una amenaza que podría acabar con todo.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/aot_t1.jpg', 25),
('Shingeki no kyojin 2nd Season', 'Acción, Drama, Fantasía, Supervivencia, Misterio, Psicológico, Aventura, Shounen', 2017, 'Tras los eventos devastadores de la primera temporada, los misterios alrededor de los titanes se profundizan aún más. Eren y sus compañeros enfrentan nuevos y aterradores enemigos cuando se revela que algunos de ellos son humanos capaces de transformarse en titanes. Mientras las murallas se ven amenazadas desde dentro y fuera, secretos ocultos durante años comienzan a salir a la luz. La lucha por la supervivencia se intensifica y el destino de la humanidad está más incierto que nunca.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/aot_t2.jpg', 12),
('Shingeki no kyojin 3rd Season', 'Acción, Drama, Fantasía, Supervivencia, Misterio, Psicológico, Aventura, Shounen', 2018, 'La guerra entre los humanos y los titanes toma un giro inesperado. Mientras los secretos detrás de las murallas y los titanes siguen desvelándose, Eren y sus amigos se enfrentan a amenazas internas y externas. El gobierno, en una lucha por el control, está lleno de conspiraciones, y los héroes deberán enfrentar decisiones difíciles para proteger lo que queda de la humanidad. Nuevas alianzas y traiciones marcarán el destino de la humanidad.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/aot_t3.jpg', 22),
('Shingeki no kyojin 4th Season', 'Acción, Drama, Fantasía, Supervivencia, Misterio, Psicológico, Aventura, Shounen', 2020, 'La batalla por la supervivencia de la humanidad alcanza nuevas alturas cuando la historia da un giro radical. Con una narrativa que se traslada a nuevas tierras y nuevos personajes, el conflicto entre los habitantes de las murallas y el mundo exterior se intensifica. Eren y sus amigos se enfrentan a dilemas morales y conflictos ideológicos mientras descubren oscuros secretos sobre los orígenes de los titanes. La lucha por la libertad y la venganza lleva a los personajes a un desenlace inevitable, lleno de sacrificios y revelaciones impactantes.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/aot_t4.jpg', 28),
('Naruto', 'Acción, Aventura, Shounen, Artes marciales, Drama, Fantasía, Superpoderes, Tragedia, Comedia, Supervivencia', 2002, 'Naruto Uzumaki es un joven ninja con un gran sueño: convertirse en el Hokage, el líder más fuerte y respetado de su aldea. Sin embargo, vive marcado por el rechazo de los aldeanos, ya que dentro de él está sellado el Zorro de Nueve Colas, una bestia demoníaca que atacó la aldea años atrás. A lo largo de su viaje, Naruto forma fuertes lazos con nuevos amigos y enfrenta varios desafíos, mientras aprende valiosas lecciones sobre la amistad, la perseverancia y el sacrificio.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/naruto.jpg', 220),
('Naruto Shippuden', 'Acción, Aventura, Shounen, Artes marciales, Drama, Fantasía, Superpoderes, Tragedia, Comedia, Supervivencia', 2007, 'Después de dos años y medio de entrenamiento, Naruto regresa a su aldea, más fuerte y decidido a rescatar a su amigo Sasuke, quien ha abandonado la aldea en busca de poder. A lo largo de esta nueva etapa, Naruto enfrenta enemigos aún más poderosos y comienza a descubrir los oscuros secretos del mundo ninja, mientras el misterio detrás de la organización Akatsuki y su conexión con los jinchuuriki, como él, se hace cada vez más claro. Nuevas alianzas, traiciones y poderosas batallas marcan el tono de esta temporada.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/naruto_shippuden.jpg', 500),
('One Piece', 'Acción, Aventura, Shounen, Fantasía, Comedia, Superpoderes, Supervivencia, Drama, Artes marciales', 1999, 'Monkey D. Luffy, un joven con el sueño de convertirse en el Rey de los Piratas, zarpa en busca del legendario tesoro conocido como el "One Piece". A lo largo de su viaje, Luffy recluta a varios compañeros con habilidades únicas, enfrentando peligrosos enemigos y descubriendo secretos ocultos en un mundo lleno de islas misteriosas, mares tempestuosos y aventuras emocionantes. La lealtad, la amistad y la determinación son los pilares que guiarán a Luffy en su misión por conquistar el Grand Line.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/one_piece.jpg', 1126),
('Death Note', 'Psicológico, Suspenso, Thriller, Shounen, Detectives, Drama, Crimen, Superpoderes, Misterio', 2006, 'Light Yagami, un brillante estudiante de secundaria, encuentra un cuaderno con un poder sobrenatural: la "Death Note", una libreta capaz de matar a cualquier persona cuyo nombre sea escrito en ella. Usando este poder, Light busca crear un mundo libre de criminales, pero pronto se enfrenta a L, un detective excepcionalmente inteligente que está decidido a detenerlo. La batalla intelectual entre Light y L se convierte en un juego de astucia, moralidad y justicia que pone a prueba los límites de la mente humana.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/death_note.jpg', 37),
('Fullmetal Alchemist', 'Acción, Aventura, Shounen, Fantasía, Drama, Superpoderes, Alquimia, Psicológico, Tragedia', 2003, 'Edward y Alphonse Elric, dos hermanos alquimistas, intentan revivir a su madre utilizando la alquimia, pero el experimento sale mal, y Edward pierde una pierna mientras que Alphonse pierde todo su cuerpo, quedando su alma atrapada en una armadura. Con el objetivo de recuperar sus cuerpos, los hermanos buscan la Piedra Filosofal, un artefacto legendario que les otorgaría el poder para restaurar lo perdido. En su viaje, se enfrentan a oscuros secretos sobre la alquimia, la política y la guerra.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/fma.jpg', 51),
('Fullmetal Alchemist: Brotherhood', 'Acción, Aventura, Shounen, Fantasía, Drama, Superpoderes, Alquimia, Psicológico, Tragedia', 2009, 'Después de que un experimento de alquimia sale terriblemente mal, los hermanos Elric, Edward y Alphonse, buscan la Piedra Filosofal para restaurar lo que han perdido: Edward su pierna y brazo, y Alphonse todo su cuerpo. A lo largo de su viaje, descubren secretos oscuros sobre la alquimia, el gobierno y una conspiración global que podría destruir el mundo. Con aliados y enemigos poderosos, los hermanos deben confrontar la verdad detrás de la Piedra Filosofal y la verdadera naturaleza de su sacrificio.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/fmab.jpg', 64),
('Kimetsu no Yaiba', 'Acción, Aventura, Shounen, Fantasía, Superpoderes, Drama, Artes marciales, Sobrenatural, Tragedia', 2019, 'Tanjiro Kamado es un joven que vive en las montañas junto a su familia. Tras regresar un día a casa, encuentra a su familia masacrada por demonios, y su hermana Nezuko es convertida en un demonio. Decidido a salvarla y vengar a su familia, Tanjiro se une a los Cazadores de Demonios, una organización dedicada a exterminar a los demonios. A lo largo de su viaje, Tanjiro se enfrenta a poderosos enemigos, mientras descubre oscuros secretos sobre los demonios y sus propias habilidades.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/kimetsu_t1.jpg', 26),
('Kimetsu no Yaiba - Tren Infinto', 'Acción, Aventura, Shounen, Fantasía, Superpoderes, Drama, Artes marciales, Sobrenatural, Tragedia', 2020, 'Tanjiro acompañado de Inosuke Hashibira y Zenitsu Agatsuma aceptan colaborar conjuntamente con el Pilar de la llama, Kyojuro Rengoku para encontrar a un Demonio responsable de numerosas desapariciones de personas a bordo de un tren además de aprovechar el viaje para buscar pistas sobre la Respiración del Sol. Poco después de subir, terminan cayendo en un profundo sueño producto del demonio, Enmu, miembro inferior de las Doce Lunas Demoníacas, enviado por Muzan Kibutsuji para matar a Tanjiro y el resto de Cazadores de Demonios bajo la promesa de obtener más poder y ascender en su organización.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/kimetsu_tren_infinito.jpg', 1),
('Kimetsu no Yaiba - Distrito Rojo', 'Acción, Aventura, Shounen, Fantasía, Superpoderes, Drama, Artes marciales, Sobrenatural, Tragedia', 2021, 'La devastación del incidente del Tren infinito aún pesa sobre los miembros del Cuerpo de Cazadores de Demonios. A pesar de que se les ha dado tiempo para recomponerse, Tanjiro y sus compañeros deben acurdir a una misión con el Pilar del sonido, Tengen Uzui ya que un sangriento demonio está aterrorizando a las mujeres y clientes del Distrito rojo de Yoshiwara.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/kimetsu_t2.jpg', 18),
('Kimetsu no Yaiba - Aldea de los herreros', 'Acción, Aventura, Shounen, Fantasía, Superpoderes, Drama, Artes marciales, Sobrenatural, Tragedia', 2023, 'Después de su ardua batalla en el Distrito Rojo, Tanjiro viaja al Pueblo de los Herreros para reparar su espada, consiguiendo una espada antigua con un pasado inédito. Allí se encuentra con el Pilar del Amor, Mitsuri Kanroji, y el Pilar de la Niebla, Muichiro Tokito. Inesperadamente, son atacados por dos poderosos demonios, las Lunas Superiores: Hantengu y Gyokko. Tanjiro junto a los Pilares deben enfrentarse a estos enemigos superando sus límites con el fin de proteger a los herreros.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/kimetsu_t3.jpg', 11),
('Kimetsu no Yaiba - Entrenamiento de los Pilares', 'Acción, Aventura, Shounen, Fantasía, Superpoderes, Drama, Artes marciales, Sobrenatural, Tragedia', 2024, 'Después de las intensas batallas en el Pueblo de los Herreros, Tanjiro y sus amigos se embarcan en un nuevo desafío: un riguroso entrenamiento con los Pilares para mejorar sus habilidades y prepararse para las batallas futuras. Bajo la supervisión de los Pilares, cada uno de los cazadores de demonios debe enfrentar sus propios límites y superar pruebas extremadamente difíciles. Mientras tanto, los demonios planean una batalla final contra los cazadores de demonios en la que estará en juego el futuro de la humanidad.', 'https://raw.githubusercontent.com/Eloycorme3/anime-imagenes/main/kimetsu_t4.jpg', 8);
