/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.controladorPrincipal;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Formacion3
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEjecutarPrimerListado = new javax.swing.JButton();
        btnEjecutarSegundoListado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPrimerListado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSegundoListado = new javax.swing.JTextArea();
        txtAnimeSegundoListado = new javax.swing.JTextField();
        txtCapitulosMaxSegundoListado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEjecutarPrimerListadoCompleto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taPrimerListadoCompleto = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnEjecutarSegundoListadoCompleto = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        taSegundoListadoCompleto = new javax.swing.JTextArea();
        txtValoracionPrimerListado = new javax.swing.JTextField();
        txtUsuarioPrimerListado = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        menuItemVolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        panel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Usuario         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 0, 15);
        panel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Valoración");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Anime");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Capítulos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel4, gridBagConstraints);

        btnEjecutarPrimerListado.setText("Ejecutar");
        btnEjecutarPrimerListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarPrimerListadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 50);
        panel.add(btnEjecutarPrimerListado, gridBagConstraints);

        btnEjecutarSegundoListado.setText("Ejecutar");
        btnEjecutarSegundoListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarSegundoListadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 50);
        panel.add(btnEjecutarSegundoListado, gridBagConstraints);

        taPrimerListado.setColumns(20);
        taPrimerListado.setRows(5);
        jScrollPane1.setViewportView(taPrimerListado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 75;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 50);
        panel.add(jScrollPane1, gridBagConstraints);

        taSegundoListado.setColumns(20);
        taSegundoListado.setRows(5);
        jScrollPane2.setViewportView(taSegundoListado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 75;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 50, 50);
        panel.add(jScrollPane2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 15);
        panel.add(txtAnimeSegundoListado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 15);
        panel.add(txtCapitulosMaxSegundoListado, gridBagConstraints);

        jLabel5.setText("Listado de animes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 15);
        panel.add(jLabel5, gridBagConstraints);

        btnEjecutarPrimerListadoCompleto.setText("Ejecutar");
        btnEjecutarPrimerListadoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarPrimerListadoCompletoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 50);
        panel.add(btnEjecutarPrimerListadoCompleto, gridBagConstraints);

        taPrimerListadoCompleto.setColumns(20);
        taPrimerListadoCompleto.setRows(5);
        jScrollPane3.setViewportView(taPrimerListadoCompleto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 75;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 50);
        panel.add(jScrollPane3, gridBagConstraints);

        jLabel6.setText("Listado de usuarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 15);
        panel.add(jLabel6, gridBagConstraints);

        btnEjecutarSegundoListadoCompleto.setText("Ejecutar");
        btnEjecutarSegundoListadoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarSegundoListadoCompletoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 50);
        panel.add(btnEjecutarSegundoListadoCompleto, gridBagConstraints);

        taSegundoListadoCompleto.setColumns(20);
        taSegundoListadoCompleto.setRows(5);
        jScrollPane4.setViewportView(taSegundoListadoCompleto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 75;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 50, 50);
        panel.add(jScrollPane4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 15);
        panel.add(txtValoracionPrimerListado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 15);
        panel.add(txtUsuarioPrimerListado, gridBagConstraints);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        menuOpciones.setText("Opciones");

        menuItemVolver.setText("Volver");
        menuItemVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVolverActionPerformed(evt);
            }
        });
        menuOpciones.add(menuItemVolver);

        menuBar.add(menuOpciones);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        controladorPrincipal.iniciarGestorAdministrador();
    }//GEN-LAST:event_menuItemVolverActionPerformed

    private void btnEjecutarPrimerListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarPrimerListadoActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.ejecutarPrimerListado();
    }//GEN-LAST:event_btnEjecutarPrimerListadoActionPerformed

    private void btnEjecutarSegundoListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarSegundoListadoActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.ejecutarSegundoListado();
    }//GEN-LAST:event_btnEjecutarSegundoListadoActionPerformed

    private void btnEjecutarPrimerListadoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarPrimerListadoCompletoActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.ejecutarPrimerListadoCompleto();
    }//GEN-LAST:event_btnEjecutarPrimerListadoCompletoActionPerformed

    private void btnEjecutarSegundoListadoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarSegundoListadoCompletoActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.ejecutarSegundoListadoCompleto();
    }//GEN-LAST:event_btnEjecutarSegundoListadoCompletoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        btnEjecutarPrimerListado.doClick();
        btnEjecutarSegundoListado.doClick();
        btnEjecutarPrimerListadoCompleto.doClick();
        btnEjecutarSegundoListadoCompleto.doClick();
    }//GEN-LAST:event_formComponentShown

    public JButton getBtnEjecutarPrimerListado() {
        return btnEjecutarPrimerListado;
    }

    public void setBtnEjecutarPrimerListado(JButton btnEjecutarPrimerListado) {
        this.btnEjecutarPrimerListado = btnEjecutarPrimerListado;
    }

    public JButton getBtnEjecutarPrimerListadoCompleto() {
        return btnEjecutarPrimerListadoCompleto;
    }

    public void setBtnEjecutarPrimerListadoCompleto(JButton btnEjecutarPrimerListadoCompleto) {
        this.btnEjecutarPrimerListadoCompleto = btnEjecutarPrimerListadoCompleto;
    }

    public JButton getBtnEjecutarSegundoListado() {
        return btnEjecutarSegundoListado;
    }

    public void setBtnEjecutarSegundoListado(JButton btnEjecutarSegundoListado) {
        this.btnEjecutarSegundoListado = btnEjecutarSegundoListado;
    }

    public JButton getBtnEjecutarSegundoListadoCompleto() {
        return btnEjecutarSegundoListadoCompleto;
    }

    public void setBtnEjecutarSegundoListadoCompleto(JButton btnEjecutarSegundoListadoCompleto) {
        this.btnEjecutarSegundoListadoCompleto = btnEjecutarSegundoListadoCompleto;
    }
    
    public JTextField getTxtAnimeSegundoListado() {
        return txtAnimeSegundoListado;
    }

    public void setTxtAnimeSegundoListado(JTextField txtAnimeSegundoListado) {
        this.txtAnimeSegundoListado = txtAnimeSegundoListado;
    }

    public JTextField getTxtCapitulosMaxSegundoListado() {
        return txtCapitulosMaxSegundoListado;
    }

    public void setTxtCapitulosMaxSegundoListado(JTextField txtCapitulosMaxSegundoListado) {
        this.txtCapitulosMaxSegundoListado = txtCapitulosMaxSegundoListado;
    }

    public JTextField getTxtUsuarioPrimerListado() {
        return txtUsuarioPrimerListado;
    }

    public void setTxtUsuarioPrimerListado(JTextField txtUsuarioPrimerListado) {
        this.txtUsuarioPrimerListado = txtUsuarioPrimerListado;
    }

    public JTextField getTxtValoracionPrimerListado() {
        return txtValoracionPrimerListado;
    }

    public void setTxtValoracionPrimerListado(JTextField txtValoracionPrimerListado) {
        this.txtValoracionPrimerListado = txtValoracionPrimerListado;
    }

    public JTextArea getTaPrimerListado() {
        return taPrimerListado;
    }

    public void setTaPrimerListado(JTextArea taPrimerListado) {
        this.taPrimerListado = taPrimerListado;
    }

    public JTextArea getTaPrimerListadoCompleto() {
        return taPrimerListadoCompleto;
    }

    public void setTaPrimerListadoCompleto(JTextArea taPrimerListadoCompleto) {
        this.taPrimerListadoCompleto = taPrimerListadoCompleto;
    }

    public JTextArea getTaSegundoListado() {
        return taSegundoListado;
    }

    public void setTaSegundoListado(JTextArea taSegundoListado) {
        this.taSegundoListado = taSegundoListado;
    }

    public JTextArea getTaSegundoListadoCompleto() {
        return taSegundoListadoCompleto;
    }

    public void setTaSegundoListadoCompleto(JTextArea taSegundoListadoCompleto) {
        this.taSegundoListadoCompleto = taSegundoListadoCompleto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutarPrimerListado;
    private javax.swing.JButton btnEjecutarPrimerListadoCompleto;
    private javax.swing.JButton btnEjecutarSegundoListado;
    private javax.swing.JButton btnEjecutarSegundoListadoCompleto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemVolver;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea taPrimerListado;
    private javax.swing.JTextArea taPrimerListadoCompleto;
    private javax.swing.JTextArea taSegundoListado;
    private javax.swing.JTextArea taSegundoListadoCompleto;
    private javax.swing.JTextField txtAnimeSegundoListado;
    private javax.swing.JTextField txtCapitulosMaxSegundoListado;
    private javax.swing.JTextField txtUsuarioPrimerListado;
    private javax.swing.JTextField txtValoracionPrimerListado;
    // End of variables declaration//GEN-END:variables
}
