/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorPrincipal;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import modelo.vo.Anime;
import modelo.vo.Usuario;

/**
 *
 * @author Acceso a datos
 */
public class GestorYConsultas extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoBase
     */
    public GestorYConsultas() {
        initComponents();
        controladorPrincipal.iniciarSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        btnAltaUsuario = new javax.swing.JButton();
        btnBajaUsuario = new javax.swing.JButton();
        btnModUsuario = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnAltaFavorito = new javax.swing.JButton();
        btnModFavorito = new javax.swing.JButton();
        btnBajaFavorito = new javax.swing.JButton();
        btnCerrarSession = new javax.swing.JButton();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNombreAnime = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtIdAnime = new javax.swing.JTextField();
        btnAltaAnime = new javax.swing.JButton();
        btnBajaAnime = new javax.swing.JButton();
        btnModAnime = new javax.swing.JButton();
        txtCategorias = new javax.swing.JTextField();
        txtAnhoSalida = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCapTotales = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboTipoUsuario = new javax.swing.JComboBox<>();
        cbVerPasswordFavoritos = new javax.swing.JCheckBox();
        spValoracion = new javax.swing.JSpinner();
        comboAnimesFavoritos = new javax.swing.JComboBox<>();
        comboFavoritosUsuarios = new javax.swing.JComboBox<>();
        spCapActual = new javax.swing.JSpinner();
        txtImagen = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPasswordFavoritos = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setText("Usuarios");

        jLabel8.setText("Id");

        jLabel9.setText("Contraseña");

        txtIdUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdUsuarioFocusLost(evt);
            }
        });

        btnAltaUsuario.setText("Alta");
        btnAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaUsuarioActionPerformed(evt);
            }
        });

        btnBajaUsuario.setText("Baja");
        btnBajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaUsuarioActionPerformed(evt);
            }
        });

        btnModUsuario.setText("Modificar");
        btnModUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModUsuarioActionPerformed(evt);
            }
        });

        jLabel11.setText("Favoritos");

        jLabel12.setText("Anime");

        jLabel13.setText("Usuario");

        jLabel14.setText("Valoración");

        jLabel15.setText("Capítulo Actual");

        btnAltaFavorito.setText("Alta");
        btnAltaFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaFavoritoActionPerformed(evt);
            }
        });

        btnModFavorito.setText("Modificar");
        btnModFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModFavoritoActionPerformed(evt);
            }
        });

        btnBajaFavorito.setText("Baja");
        btnBajaFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaFavoritoActionPerformed(evt);
            }
        });

        btnCerrarSession.setText("Cerrar Sesion");
        btnCerrarSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSessionActionPerformed(evt);
            }
        });

        txtNombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreUsuarioFocusLost(evt);
            }
        });

        jLabel18.setText("Nombre");

        txtNombreAnime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreAnimeFocusLost(evt);
            }
        });

        jLabel19.setText("Nombre");

        jLabel10.setText("Animes");

        jLabel20.setText("Id");

        txtIdAnime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdAnimeFocusLost(evt);
            }
        });

        btnAltaAnime.setText("Alta");
        btnAltaAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaAnimeActionPerformed(evt);
            }
        });

        btnBajaAnime.setText("Baja");
        btnBajaAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaAnimeActionPerformed(evt);
            }
        });

        btnModAnime.setText("Modificar");
        btnModAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModAnimeActionPerformed(evt);
            }
        });

        jLabel22.setText("Categorias");

        jLabel23.setText("Año Salida");

        jLabel24.setText("Descripción");

        jLabel25.setText("Capítulos totales");

        jLabel17.setText("Tipo");

        cbVerPasswordFavoritos.setText("Ver contraseña");
        cbVerPasswordFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVerPasswordFavoritosActionPerformed(evt);
            }
        });

        spValoracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        comboFavoritosUsuarios.setToolTipText("");
        comboFavoritosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFavoritosUsuariosActionPerformed(evt);
            }
        });

        spCapActual.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jLabel26.setText("Imagen");

        txtPasswordFavoritos.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel11))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spValoracion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spCapActual)
                                    .addComponent(comboAnimesFavoritos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboFavoritosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAltaFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBajaFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel17))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(16, 16, 16)))
                                            .addComponent(jLabel18))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNombreUsuario)
                                            .addComponent(txtIdUsuario)
                                            .addComponent(comboTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPasswordFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnAltaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnBajaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnModUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbVerPasswordFavoritos))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtNombreAnime)
                                                    .addComponent(txtIdAnime)
                                                    .addComponent(txtCategorias)
                                                    .addComponent(txtAnhoSalida)
                                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(15, 15, 15)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnAltaAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnBajaAnime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnModAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCapTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(btnCerrarSession, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAltaUsuario)
                            .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModUsuario)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasswordFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbVerPasswordFavoritos)
                            .addComponent(jLabel9))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBajaUsuario)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdAnime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreAnime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22))
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAnhoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAltaAnime)
                                        .addGap(15, 15, 15)
                                        .addComponent(btnModAnime)
                                        .addGap(15, 15, 15)
                                        .addComponent(btnBajaAnime)))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addGap(15, 15, 15)
                                .addComponent(txtCapTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFavoritosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaFavorito)
                    .addComponent(comboAnimesFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModFavorito)
                    .addComponent(spValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBajaFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spCapActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(29, 29, 29)
                .addComponent(btnCerrarSession)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtIdUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdUsuarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioFocusLost

    private void btnAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaUsuarioActionPerformed

    private void btnModUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModUsuarioActionPerformed

    private void btnBajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaUsuarioActionPerformed

    private void btnAltaFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaFavoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaFavoritoActionPerformed

    private void btnModFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModFavoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModFavoritoActionPerformed

    private void btnBajaFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaFavoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaFavoritoActionPerformed

    private void btnCerrarSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSessionActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.cerrarSesionUsuario();
        controladorPrincipal.iniciarLogin();
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSessionActionPerformed

    private void txtNombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreUsuarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioFocusLost

    private void txtNombreAnimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreAnimeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAnimeFocusLost

    private void txtIdAnimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdAnimeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAnimeFocusLost

    private void btnAltaAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaAnimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaAnimeActionPerformed

    private void btnBajaAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaAnimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaAnimeActionPerformed

    private void btnModAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModAnimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModAnimeActionPerformed

    private void comboFavoritosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFavoritosUsuariosActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.cargarComboAnimes();
    }//GEN-LAST:event_comboFavoritosUsuariosActionPerformed

    private void cbVerPasswordFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVerPasswordFavoritosActionPerformed
        // TODO add your handling code here:
        if (cbVerPasswordFavoritos.isSelected()) {
            txtPasswordFavoritos.setEchoChar((char) 0);
        } else {
            txtPasswordFavoritos.setEchoChar('*');
        }
    }//GEN-LAST:event_cbVerPasswordFavoritosActionPerformed

    public JCheckBox getCbVerPasswordFavoritos() {
        return cbVerPasswordFavoritos;
    }

    public void setCbVerPasswordFavoritos(JCheckBox cbVerPasswordFavoritos) {
        this.cbVerPasswordFavoritos = cbVerPasswordFavoritos;
    }

    public JComboBox<Anime> getComboAnimesFavoritos() {
        return comboAnimesFavoritos;
    }

    public void setComboAnimesFavoritos(JComboBox<Anime> comboAnimesFavoritos) {
        this.comboAnimesFavoritos = comboAnimesFavoritos;
    }

    public JComboBox<Usuario> getComboFavoritosUsuarios() {
        return comboFavoritosUsuarios;
    }

    public void setComboFavoritosUsuarios(JComboBox<Usuario> comboFavoritosUsuarios) {
        this.comboFavoritosUsuarios = comboFavoritosUsuarios;
    }

    public JComboBox<String> getComboTipoUsuario() {
        return comboTipoUsuario;
    }

    public void setComboTipoUsuario(JComboBox<String> comboTipoUsuario) {
        this.comboTipoUsuario = comboTipoUsuario;
    }

    public JSpinner getSpCapActual() {
        return spCapActual;
    }

    public void setSpCapActual(JSpinner spCapActual) {
        this.spCapActual = spCapActual;
    }

    public JSpinner getSpValoracion() {
        return spValoracion;
    }

    public void setSpValoracion(JSpinner spValoracion) {
        this.spValoracion = spValoracion;
    }

    public JTextField getTxtAnhoSalida() {
        return txtAnhoSalida;
    }

    public void setTxtAnhoSalida(JTextField txtAnhoSalida) {
        this.txtAnhoSalida = txtAnhoSalida;
    }

    public JTextField getTxtCapTotales() {
        return txtCapTotales;
    }

    public void setTxtCapTotales(JTextField txtCapTotales) {
        this.txtCapTotales = txtCapTotales;
    }

    public JTextField getTxtCategorias() {
        return txtCategorias;
    }

    public void setTxtCategorias(JTextField txtCategorias) {
        this.txtCategorias = txtCategorias;
    }

    public JPasswordField getTxtPasswordFavoritos() {
        return txtPasswordFavoritos;
    }

    public void setTxtPasswordFavoritos(JPasswordField txtPasswordFavoritos) {
        this.txtPasswordFavoritos = txtPasswordFavoritos;
    }

    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public void setTxtDescripcion(JTextField txtDescripcion) {
        this.txtDescripcion = txtDescripcion;
    }

    public JTextField getTxtIdAnime() {
        return txtIdAnime;
    }

    public void setTxtIdAnime(JTextField txtIdAnime) {
        this.txtIdAnime = txtIdAnime;
    }

    public JTextField getTxtIdUsuario() {
        return txtIdUsuario;
    }

    public void setTxtIdUsuario(JTextField txtIdUsuario) {
        this.txtIdUsuario = txtIdUsuario;
    }

    public JTextField getTxtImagen() {
        return txtImagen;
    }

    public void setTxtImagen(JTextField txtImagen) {
        this.txtImagen = txtImagen;
    }

    public JTextField getTxtNombreAnime() {
        return txtNombreAnime;
    }

    public void setTxtNombreAnime(JTextField txtNombreAnime) {
        this.txtNombreAnime = txtNombreAnime;
    }

    public JTextField getTxtNombreUsuario() {
        return txtNombreUsuario;
    }

    public void setTxtNombreUsuario(JTextField txtNombreUsuario) {
        this.txtNombreUsuario = txtNombreUsuario;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaAnime;
    private javax.swing.JButton btnAltaFavorito;
    private javax.swing.JButton btnAltaUsuario;
    private javax.swing.JButton btnBajaAnime;
    private javax.swing.JButton btnBajaFavorito;
    private javax.swing.JButton btnBajaUsuario;
    private javax.swing.JButton btnCerrarSession;
    private javax.swing.JButton btnModAnime;
    private javax.swing.JButton btnModFavorito;
    private javax.swing.JButton btnModUsuario;
    private javax.swing.JCheckBox cbVerPasswordFavoritos;
    private javax.swing.JComboBox<Anime> comboAnimesFavoritos;
    private javax.swing.JComboBox<Usuario> comboFavoritosUsuarios;
    private javax.swing.JComboBox<String> comboTipoUsuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spCapActual;
    private javax.swing.JSpinner spValoracion;
    private javax.swing.JTextField txtAnhoSalida;
    private javax.swing.JTextField txtCapTotales;
    private javax.swing.JTextField txtCategorias;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdAnime;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombreAnime;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPasswordFavoritos;
    // End of variables declaration//GEN-END:variables
}
