/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.controladorPrincipal;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author eloy.castro
 */
public class GestorUsuario extends javax.swing.JFrame {

    /**
     * Creates new form GestorUsuarios
     */
    public GestorUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel = new javax.swing.JPanel();
        btnBajaUsuarios = new javax.swing.JButton();
        btnModContrasenhaUsuario = new javax.swing.JButton();
        btnModNombreUsuario = new javax.swing.JButton();
        cbVerPassword = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtPasswordUsuario = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel.setLayout(new java.awt.GridBagLayout());

        btnBajaUsuarios.setText("Eliminar Usuario");
        btnBajaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaUsuariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(40, 15, 50, 50);
        panel.add(btnBajaUsuarios, gridBagConstraints);

        btnModContrasenhaUsuario.setText("Cambiar contraseña");
        btnModContrasenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModContrasenhaUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 50);
        panel.add(btnModContrasenhaUsuario, gridBagConstraints);

        btnModNombreUsuario.setText("Cambiar nombre");
        btnModNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModNombreUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 50);
        panel.add(btnModNombreUsuario, gridBagConstraints);

        cbVerPassword.setText("Mostrar contraseña");
        cbVerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVerPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(cbVerPassword, gridBagConstraints);

        jLabel5.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 20);
        panel.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panel.add(txtNombreUsuario, gridBagConstraints);

        txtPasswordUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panel.add(txtPasswordUsuario, gridBagConstraints);

        jLabel3.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 20);
        panel.add(jLabel3, gridBagConstraints);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        menuOpciones.setText("Opciones");

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuOpciones.add(menuItemSalir);

        menuBar.add(menuOpciones);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbVerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVerPasswordActionPerformed
        // TODO add your handling code here:
        if (cbVerPassword.isSelected()) {
            txtPasswordUsuario.setEchoChar((char) 0);
        } else {
            txtPasswordUsuario.setEchoChar('*');
        }
    }//GEN-LAST:event_cbVerPasswordActionPerformed

    private void txtPasswordUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordUsuarioActionPerformed

    private void btnBajaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaUsuariosActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.darBajaUsuario();
    }//GEN-LAST:event_btnBajaUsuariosActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnModContrasenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModContrasenhaUsuarioActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.modificarContrasenhaUsuario();
    }//GEN-LAST:event_btnModContrasenhaUsuarioActionPerformed

    private void btnModNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModNombreUsuarioActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.modificarNombreUsuario();
    }//GEN-LAST:event_btnModNombreUsuarioActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.cerrarSesionUsuario();
        this.setVisible(false);
        controladorPrincipal.iniciarLogin();
    }//GEN-LAST:event_menuItemSalirActionPerformed

    public JCheckBox getCbVerPassword() {
        return cbVerPassword;
    }

    public void setCbVerPassword(JCheckBox cbVerPassword) {
        this.cbVerPassword = cbVerPassword;
    }

    public JTextField getTxtNombreUsuario() {
        return txtNombreUsuario;
    }

    public void setTxtNombreUsuario(JTextField txtNombreUsuario) {
        this.txtNombreUsuario = txtNombreUsuario;
    }

    public JPasswordField getTxtPasswordUsuario() {
        return txtPasswordUsuario;
    }

    public void setTxtPasswordUsuario(JPasswordField txtPasswordUsuario) {
        this.txtPasswordUsuario = txtPasswordUsuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajaUsuarios;
    private javax.swing.JButton btnModContrasenhaUsuario;
    private javax.swing.JButton btnModNombreUsuario;
    private javax.swing.JCheckBox cbVerPassword;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPasswordUsuario;
    // End of variables declaration//GEN-END:variables
}
