/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorPrincipal;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import modelo.vo.Anime;
import modelo.vo.Usuario;

/**
 *
 * @author Acceso a datos
 */
public class GestorYConsultas extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoBase
     */
    public GestorYConsultas() {
        initComponents();
        controladorPrincipal.iniciarSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnModFavorito = new javax.swing.JButton();
        comboTipoUsuario = new javax.swing.JComboBox<>();
        btnBajaFavorito = new javax.swing.JButton();
        cbVerPasswordFavoritos = new javax.swing.JCheckBox();
        spValoracion = new javax.swing.JSpinner();
        txtNombreUsuario = new javax.swing.JTextField();
        comboAnimesFavoritos = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        comboFavoritosUsuarios = new javax.swing.JComboBox<>();
        txtNombreAnime = new javax.swing.JTextField();
        spCapActual = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtIdAnime = new javax.swing.JTextField();
        txtPasswordFavoritos = new javax.swing.JPasswordField();
        btnAltaAnime = new javax.swing.JButton();
        btnBajaAnime = new javax.swing.JButton();
        txtIdUsuario = new javax.swing.JTextField();
        btnModAnime = new javax.swing.JButton();
        btnAltaUsuario = new javax.swing.JButton();
        txtCategorias = new javax.swing.JTextField();
        btnBajaUsuario = new javax.swing.JButton();
        txtAnhoSalida = new javax.swing.JTextField();
        btnModUsuario = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCapTotales = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnAltaFavorito = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("Usuarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 15);
        panel.add(jLabel7, gridBagConstraints);

        jLabel25.setText("Capítulos totales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel25, gridBagConstraints);

        jLabel8.setText("Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel8, gridBagConstraints);

        jLabel17.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel17, gridBagConstraints);

        jLabel9.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel9, gridBagConstraints);

        btnModFavorito.setText("Modificar");
        btnModFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModFavoritoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        panel.add(btnModFavorito, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(comboTipoUsuario, gridBagConstraints);

        btnBajaFavorito.setText("Baja");
        btnBajaFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaFavoritoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 50, 0);
        panel.add(btnBajaFavorito, gridBagConstraints);

        cbVerPasswordFavoritos.setText("Ver contraseña");
        cbVerPasswordFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVerPasswordFavoritosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        panel.add(cbVerPasswordFavoritos, gridBagConstraints);

        spValoracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(spValoracion, gridBagConstraints);

        txtNombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreUsuarioFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtNombreUsuario, gridBagConstraints);

        comboAnimesFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAnimesFavoritosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(comboAnimesFavoritos, gridBagConstraints);

        jLabel18.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel18, gridBagConstraints);

        comboFavoritosUsuarios.setToolTipText("");
        comboFavoritosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFavoritosUsuariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(comboFavoritosUsuarios, gridBagConstraints);

        txtNombreAnime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreAnimeFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtNombreAnime, gridBagConstraints);

        spCapActual.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 50, 0);
        panel.add(spCapActual, gridBagConstraints);

        jLabel19.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel19, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtImagen, gridBagConstraints);

        jLabel10.setText("Animes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 15);
        panel.add(jLabel10, gridBagConstraints);

        jLabel26.setText("Imagen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel26, gridBagConstraints);

        jLabel20.setText("Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel20, gridBagConstraints);

        txtIdAnime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdAnimeFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtIdAnime, gridBagConstraints);

        txtPasswordFavoritos.setText("jPasswordField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtPasswordFavoritos, gridBagConstraints);

        btnAltaAnime.setText("Alta");
        btnAltaAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaAnimeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 50);
        panel.add(btnAltaAnime, gridBagConstraints);

        btnBajaAnime.setText("Baja");
        btnBajaAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaAnimeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 50);
        panel.add(btnBajaAnime, gridBagConstraints);

        txtIdUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdUsuarioFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtIdUsuario, gridBagConstraints);

        btnModAnime.setText("Modificar");
        btnModAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModAnimeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 50);
        panel.add(btnModAnime, gridBagConstraints);

        btnAltaUsuario.setText("Alta");
        btnAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        panel.add(btnAltaUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtCategorias, gridBagConstraints);

        btnBajaUsuario.setText("Baja");
        btnBajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        panel.add(btnBajaUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtAnhoSalida, gridBagConstraints);

        btnModUsuario.setText("Modificar");
        btnModUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        panel.add(btnModUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtDescripcion, gridBagConstraints);

        jLabel11.setText("Favoritos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 15);
        panel.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panel.add(txtCapTotales, gridBagConstraints);

        jLabel12.setText("Anime");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel12, gridBagConstraints);

        jLabel22.setText("Categorias");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel22, gridBagConstraints);

        jLabel13.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel13, gridBagConstraints);

        jLabel23.setText("Año Salida");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel23, gridBagConstraints);

        jLabel14.setText("Valoración");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel14, gridBagConstraints);

        jLabel24.setText("Descripción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel24, gridBagConstraints);

        jLabel15.setText("Capítulo Actual");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 50, 15);
        panel.add(jLabel15, gridBagConstraints);

        btnAltaFavorito.setText("Alta");
        btnAltaFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaFavoritoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        panel.add(btnAltaFavorito, gridBagConstraints);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        menuOpciones.setText("Opciones");

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuOpciones.add(menuItemSalir);

        menuBar.add(menuOpciones);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtIdUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdUsuarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioFocusLost

    private void btnAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaUsuarioActionPerformed

    private void btnModUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModUsuarioActionPerformed

    private void btnBajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaUsuarioActionPerformed

    private void btnAltaFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaFavoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaFavoritoActionPerformed

    private void btnModFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModFavoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModFavoritoActionPerformed

    private void btnBajaFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaFavoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaFavoritoActionPerformed

    private void txtNombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreUsuarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioFocusLost

    private void txtNombreAnimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreAnimeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAnimeFocusLost

    private void txtIdAnimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdAnimeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAnimeFocusLost

    private void btnAltaAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaAnimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaAnimeActionPerformed

    private void btnBajaAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaAnimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaAnimeActionPerformed

    private void btnModAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModAnimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModAnimeActionPerformed

    private void comboFavoritosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFavoritosUsuariosActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.cargarComboAnimes();
    }//GEN-LAST:event_comboFavoritosUsuariosActionPerformed

    private void cbVerPasswordFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVerPasswordFavoritosActionPerformed
        // TODO add your handling code here:
        if (cbVerPasswordFavoritos.isSelected()) {
            txtPasswordFavoritos.setEchoChar((char) 0);
        } else {
            txtPasswordFavoritos.setEchoChar('*');
        }
    }//GEN-LAST:event_cbVerPasswordFavoritosActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.cerrarSesionUsuario();
        this.setVisible(false);
        controladorPrincipal.iniciarLogin();
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void comboAnimesFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAnimesFavoritosActionPerformed
        // TODO add your handling code here:
        controladorPrincipal.fijarCapitulos();
        controladorPrincipal.fijarValoracion();
    }//GEN-LAST:event_comboAnimesFavoritosActionPerformed

    public JCheckBox getCbVerPasswordFavoritos() {
        return cbVerPasswordFavoritos;
    }

    public void setCbVerPasswordFavoritos(JCheckBox cbVerPasswordFavoritos) {
        this.cbVerPasswordFavoritos = cbVerPasswordFavoritos;
    }

    public JComboBox<Anime> getComboAnimesFavoritos() {
        return comboAnimesFavoritos;
    }

    public void setComboAnimesFavoritos(JComboBox<Anime> comboAnimesFavoritos) {
        this.comboAnimesFavoritos = comboAnimesFavoritos;
    }

    public JComboBox<Usuario> getComboFavoritosUsuarios() {
        return comboFavoritosUsuarios;
    }

    public void setComboFavoritosUsuarios(JComboBox<Usuario> comboFavoritosUsuarios) {
        this.comboFavoritosUsuarios = comboFavoritosUsuarios;
    }

    public JComboBox<String> getComboTipoUsuario() {
        return comboTipoUsuario;
    }

    public void setComboTipoUsuario(JComboBox<String> comboTipoUsuario) {
        this.comboTipoUsuario = comboTipoUsuario;
    }

    public JSpinner getSpCapActual() {
        return spCapActual;
    }

    public void setSpCapActual(JSpinner spCapActual) {
        this.spCapActual = spCapActual;
    }

    public JSpinner getSpValoracion() {
        return spValoracion;
    }

    public void setSpValoracion(JSpinner spValoracion) {
        this.spValoracion = spValoracion;
    }

    public JTextField getTxtAnhoSalida() {
        return txtAnhoSalida;
    }

    public void setTxtAnhoSalida(JTextField txtAnhoSalida) {
        this.txtAnhoSalida = txtAnhoSalida;
    }

    public JTextField getTxtCapTotales() {
        return txtCapTotales;
    }

    public void setTxtCapTotales(JTextField txtCapTotales) {
        this.txtCapTotales = txtCapTotales;
    }

    public JTextField getTxtCategorias() {
        return txtCategorias;
    }

    public void setTxtCategorias(JTextField txtCategorias) {
        this.txtCategorias = txtCategorias;
    }

    public JPasswordField getTxtPasswordFavoritos() {
        return txtPasswordFavoritos;
    }

    public void setTxtPasswordFavoritos(JPasswordField txtPasswordFavoritos) {
        this.txtPasswordFavoritos = txtPasswordFavoritos;
    }

    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public void setTxtDescripcion(JTextField txtDescripcion) {
        this.txtDescripcion = txtDescripcion;
    }

    public JTextField getTxtIdAnime() {
        return txtIdAnime;
    }

    public void setTxtIdAnime(JTextField txtIdAnime) {
        this.txtIdAnime = txtIdAnime;
    }

    public JTextField getTxtIdUsuario() {
        return txtIdUsuario;
    }

    public void setTxtIdUsuario(JTextField txtIdUsuario) {
        this.txtIdUsuario = txtIdUsuario;
    }

    public JTextField getTxtImagen() {
        return txtImagen;
    }

    public void setTxtImagen(JTextField txtImagen) {
        this.txtImagen = txtImagen;
    }

    public JTextField getTxtNombreAnime() {
        return txtNombreAnime;
    }

    public void setTxtNombreAnime(JTextField txtNombreAnime) {
        this.txtNombreAnime = txtNombreAnime;
    }

    public JTextField getTxtNombreUsuario() {
        return txtNombreUsuario;
    }

    public void setTxtNombreUsuario(JTextField txtNombreUsuario) {
        this.txtNombreUsuario = txtNombreUsuario;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaAnime;
    private javax.swing.JButton btnAltaFavorito;
    private javax.swing.JButton btnAltaUsuario;
    private javax.swing.JButton btnBajaAnime;
    private javax.swing.JButton btnBajaFavorito;
    private javax.swing.JButton btnBajaUsuario;
    private javax.swing.JButton btnModAnime;
    private javax.swing.JButton btnModFavorito;
    private javax.swing.JButton btnModUsuario;
    private javax.swing.JCheckBox cbVerPasswordFavoritos;
    private javax.swing.JComboBox<Anime> comboAnimesFavoritos;
    private javax.swing.JComboBox<Usuario> comboFavoritosUsuarios;
    private javax.swing.JComboBox<String> comboTipoUsuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JPanel panel;
    private javax.swing.JSpinner spCapActual;
    private javax.swing.JSpinner spValoracion;
    private javax.swing.JTextField txtAnhoSalida;
    private javax.swing.JTextField txtCapTotales;
    private javax.swing.JTextField txtCategorias;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdAnime;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombreAnime;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPasswordFavoritos;
    // End of variables declaration//GEN-END:variables
}
