/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.controladorPrincipal;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author eloy.castro
 */
public class ReportAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ReportView
     */
    public ReportAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreParametro = new javax.swing.JTextField();
        spAnhoInicioParametro = new javax.swing.JSpinner();
        spAnhoFinParametro = new javax.swing.JSpinner();
        btnGenerarReport = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        menuItemVolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Año Inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Año Fin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 15);
        panel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 0, 15);
        panel.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 50);
        panel.add(txtNombreParametro, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 50);
        panel.add(spAnhoInicioParametro, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 50);
        panel.add(spAnhoFinParametro, gridBagConstraints);

        btnGenerarReport.setText("Generar Report");
        btnGenerarReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 50, 50);
        panel.add(btnGenerarReport, gridBagConstraints);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        menuOpciones.setText("Opciones");

        menuItemVolver.setText("Volver");
        menuItemVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVolverActionPerformed(evt);
            }
        });
        menuOpciones.add(menuItemVolver);

        menuBar.add(menuOpciones);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReportActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnGenerarReportActionPerformed

    private void menuItemVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        controladorPrincipal.iniciarGestorAdministrador();
    }//GEN-LAST:event_menuItemVolverActionPerformed

    public JSpinner getSpAnhoFinParametro() {
        return spAnhoFinParametro;
    }

    public void setSpAnhoFinParametro(JSpinner spAnhoFinParametro) {
        this.spAnhoFinParametro = spAnhoFinParametro;
    }

    public JSpinner getSpAnhoInicioParametro() {
        return spAnhoInicioParametro;
    }

    public void setSpAnhoInicioParametro(JSpinner spAnhoInicioParametro) {
        this.spAnhoInicioParametro = spAnhoInicioParametro;
    }

    public JTextField getTxtNombreParametro() {
        return txtNombreParametro;
    }

    public void setTxtNombreParametro(JTextField txtNombreParametro) {
        this.txtNombreParametro = txtNombreParametro;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemVolver;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JPanel panel;
    private javax.swing.JSpinner spAnhoFinParametro;
    private javax.swing.JSpinner spAnhoInicioParametro;
    private javax.swing.JTextField txtNombreParametro;
    // End of variables declaration//GEN-END:variables
}
